name: Get Unity License File

on:
  workflow_dispatch: # Allows you to run this manually from the UI

jobs:
  requestLicense:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Request Activation File
        id: getFile
        # Using game-ci tool to pull the raw machine fingerprint
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload Fingerprint File
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ${{ steps.getFile.outputs.filePath }}
